### ISSUE TITLE
Build mvn fails

### ISSUE THREAD

**Issue by aharth** [wintechis/ldp-sail#1]
I cannot build ldp-sail:

````
$ mvn build
...
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running de.fau.rw.ti.LDPInferencerTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[ERROR] Tests run: 7, Failures: 0, Errors: 7, Skipped: 0, Time elapsed: 0.12 s <<< FAILURE! - in de.fau.rw.ti.LDPInferencerTest
[ERROR] testRuleLdpDirect1NotMore(de.fau.rw.ti.LDPInferencerTest)  Time elapsed: 0.051 s  <<< ERROR!
java.lang.NullPointerException
	at de.fau.rw.ti.LDPInferencerTest.getFile(LDPInferencerTest.java:142)
	at de.fau.rw.ti.LDPInferencerTest.testRuleLdpDirect1NotMore(LDPInferencerTest.java:47)

[ERROR] testRuleLdpOrdered1(de.fau.rw.ti.LDPInferencerTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NullPointerException
	at de.fau.rw.ti.LDPInferencerTest.getFile(LDPInferencerTest.java:142)
	at de.fau.rw.ti.LDPInferencerTest.testRuleLdpOrdered1(LDPInferencerTest.java:93)

[ERROR] testRuleLdpIndirect1NotMore(de.fau.rw.ti.LDPInferencerTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NullPointerException
	at de.fau.rw.ti.LDPInferencerTest.getFile(LDPInferencerTest.java:142)
	at de.fau.rw.ti.LDPInferencerTest.testRuleLdpIndirect1NotMore(LDPInferencerTest.java:78)

[ERROR] testRuleLdpDirect1(de.fau.rw.ti.LDPInferencerTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NullPointerException
	at de.fau.rw.ti.LDPInferencerTest.getFile(LDPInferencerTest.java:142)
	at de.fau.rw.ti.LDPInferencerTest.testRuleLdpDirect1(LDPInferencerTest.java:31)

[ERROR] testRuleLdpOrdered1NotMore(de.fau.rw.ti.LDPInferencerTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NullPointerException
	at de.fau.rw.ti.LDPInferencerTest.getFile(LDPInferencerTest.java:142)
	at de.fau.rw.ti.LDPInferencerTest.testRuleLdpOrdered1NotMore(LDPInferencerTest.java:109)

[ERROR] testRuleLdpIndirect1(de.fau.rw.ti.LDPInferencerTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NullPointerException
	at de.fau.rw.ti.LDPInferencerTest.getFile(LDPInferencerTest.java:142)
	at de.fau.rw.ti.LDPInferencerTest.testRuleLdpIndirect1(LDPInferencerTest.java:62)

[ERROR] testLdpDirectAddedLater(de.fau.rw.ti.LDPInferencerTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NullPointerException
	at de.fau.rw.ti.LDPInferencerTest.getFile(LDPInferencerTest.java:142)
	at de.fau.rw.ti.LDPInferencerTest.testLdpDirectAddedLater(LDPInferencerTest.java:124)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   LDPInferencerTest.testLdpDirectAddedLater:124->getFile:142 NullPointer
[ERROR]   LDPInferencerTest.testRuleLdpDirect1:31->getFile:142 NullPointer
[ERROR]   LDPInferencerTest.testRuleLdpDirect1NotMore:47->getFile:142 NullPointer
[ERROR]   LDPInferencerTest.testRuleLdpIndirect1:62->getFile:142 NullPointer
[ERROR]   LDPInferencerTest.testRuleLdpIndirect1NotMore:78->getFile:142 NullPointer
[ERROR]   LDPInferencerTest.testRuleLdpOrdered1:93->getFile:142 NullPointer
[ERROR]   LDPInferencerTest.testRuleLdpOrdered1NotMore:109->getFile:142 NullPointer
[INFO] 
[ERROR] Tests run: 7, Failures: 0, Errors: 7, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.432 s
[INFO] Finished at: 2022-05-05T17:07:43+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project ldp-sail: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/aharth/projects/mosaik/scenario/ldp-sail/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
$
````

**Comment by dschraudner** [comment]
Resolved by [330f56a](https://github.com/wintechis/ldp-sail/commit/330f56a8cb8766260372a6ff5d650dcd28ce7eff).
